const { watch, src, dest, series } = require('gulp')
const del = require('del')
const fileInclude = require('gulp-file-include')
const htmlmin = require('gulp-htmlmin')
const sass = require('gulp-sass')(require('sass'))
const imagemin = require('gulp-imagemin')
const realFavicon = require('gulp-real-favicon')
const sourcemaps = require('gulp-sourcemaps')
const fs = require('fs')
const through = require('through2')
const named = require('vinyl-named')
const webpack = require('webpack-stream')
let packageJson

const paths = {
  html: {
    src: 'src/*.html',
    dest: 'dist/'
  },
  htmlinclude: 'src/include/*.html',
  img: {
    src: 'src/assets/img/*',
    dest: 'dist/assets/img/'
  },
  js: {
    src: ['src/assets/js/first.js', 'src/assets/js/app.js'],
    dest: 'dist/assets/js/',
    watch: 'src/assets/js/*.js'
  },
  scss: {
    src: 'src/assets/scss/*.scss',
    dest: 'dist/assets/css/'
  }
}

// Get Package information from package.json
function getPackageInfo (cb) {
  packageJson = JSON.parse(fs.readFileSync('./package.json'))
  cb()
}

// Wipe the dist directory
function clean (cb) {
  del(['dist/public/', 'dist/dash/'])
  cb()
}

// Minify HTML
function html (cb) {
  src(paths.html.src)
    .pipe(fileInclude())
    .pipe(
      htmlmin({
        collapseBooleanAttributes: true,
        collapseWhitespace: true,
        includeAutoGeneratedTags: false,
        minifyURLs: true,
        removeAttributeQuotes: true,
        removeComments: true,
        removeEmptyAttributes: true,
        removeRedundantAttributes: true,
        removeScriptTypeAttributes: true,
        removeStyleLinkTypeAttributes: true
      })
    )
    .pipe(dest(paths.html.dest))
  cb()
}

// Minify JavaScript
function js (cb) {
  src(paths.js.src)
    .pipe(named())
    .pipe(
      webpack({
        devtool: 'source-map',
        mode: 'production',
        module: {
          rules: [
            {
              test: /\.js$/i,
              loader: 'string-replace-loader',
              options: {
                multiple: [
                  { search: '{commit_hash}', replace: process.env.CF_PAGES_COMMIT_SHA },
                  { search: '{branch_name}', replace: process.env.CF_PAGES_BRANCH },
                  {
                    search: '{environment}',
                    replace: process.env.CF_PAGES_BRANCH === 'main' ? 'production' : 'development'
                  },
                  { search: '{sentry_dsn}', replace: process.env.SENTRY_DSN },
                  { search: '{package_name}', replace: packageJson.name },
                  { search: '{package_version}', replace: packageJson.version }
                ]
              }
            }
          ]
        }
      })
    )
    .pipe(sourcemaps.init({ loadMaps: true }))
    .pipe(
      through.obj(function (file, enc, cba) {
        // Dont pipe through any source map files. They will be handled by gulp-sourcemaps.
        if (!/\.map$/.test(file.path)) {
          this.push(file)
        }
        cba()
      })
    )
    .pipe(sourcemaps.write('.', { addComment: false }))
    .pipe(dest(paths.js.dest))
  cb()
}

// Compile SCSS
function scss (cb) {
  src(paths.scss.src)
    .pipe(sass({ outputStyle: 'compressed' }).on('error', sass.logError))
    .pipe(dest(paths.scss.dest))
  cb()
}

// Compress images
function img (cb) {
  src(paths.img.src)
    .pipe(
      imagemin([
        imagemin.gifsicle({
          optimizationLevel: 3,
          colors: 128,
          interlaced: true
        }),
        imagemin.mozjpeg({ quality: 50, progressive: true }),
        imagemin.optipng({ optimizationLevel: 7 }),
        imagemin.svgo()
      ])
    )
    .pipe(dest(paths.img.dest))
  cb()
}

// File where the favicon markups are stored
const FAVICON_DATA_FILE = 'src/faviconData.json'

// Generate the favicon
function generateFavicon (cb) {
  return realFavicon.generateFavicon(
    {
      masterPicture: 'src/icon.png',
      dest: 'dist/',
      iconsPath: '/',
      design: {
        ios: {
          pictureAspect: 'backgroundAndMargin',
          backgroundColor: '#ffffff',
          margin: '21%',
          assets: {
            ios6AndPriorIcons: false,
            ios7AndLaterIcons: false,
            precomposedIcons: false,
            declareOnlyDefaultIcon: true
          },
          appName: 'Andrew Ensley'
        },
        desktopBrowser: {
          design: 'raw'
        },
        windows: {
          pictureAspect: 'whiteSilhouette',
          backgroundColor: '#930000',
          onConflict: 'override',
          assets: {
            windows80Ie10Tile: false,
            windows10Ie11EdgeTiles: {
              small: false,
              medium: true,
              big: false,
              rectangle: false
            }
          },
          appName: 'Andrew Ensley'
        },
        androidChrome: {
          pictureAspect: 'shadow',
          themeColor: '#ffffff',
          manifest: {
            startUrl: 'https://andrewensley.com',
            display: 'standalone',
            orientation: 'notSet',
            onConflict: 'override',
            declared: true
          },
          assets: {
            legacyIcon: false,
            lowResolutionIcons: false
          }
        },
        safariPinnedTab: {
          pictureAspect: 'silhouette',
          themeColor: '#930000'
        }
      },
      settings: {
        compression: 5,
        scalingAlgorithm: 'Mitchell',
        errorOnImageTooSmall: false,
        readmeFile: false,
        htmlCodeFile: false,
        usePathAsIs: false
      },
      markupFile: FAVICON_DATA_FILE
    },
    cb
  )
}

// Watch for changes
function watchSrc () {
  console.warn('Watching for changes... Press [CTRL+C] to stop.')
  watch([paths.html.src, paths.htmlinclude], html)
  watch(paths.scss.src, scss)
  watch(paths.img.src, img)
  watch(paths.js.watch, js)
}

exports.clean = clean
exports.html = html
exports.js = js
exports.scss = scss
exports.img = img
exports.generateFavicon = generateFavicon
exports.default = series(
  getPackageInfo,
  html,
  scss,
  img,
  js,
  generateFavicon
)
exports.watch = series(getPackageInfo, watchSrc)
